### ISSUE TITLE
Exception vs LastErrorCode / LastErrorString

### ISSUE THREAD

**Issue by mycroes** [S7NetPlus/s7netplus#137]
As the title says, use of `Exception`s vs `LastErrorCode` and `LastErrorString`. Personally I favor exceptions because they don't break under concurrent use and they're the builtin (as in within the language) solution for this problem. A custom exception type can be created to also return the error code. There are some cases where exceptions are thrown on precondition failures while in other cases the error code and message are set, I think this should be implemented consistently.

**Comment by rapha-dev** [comment]
Agreed. Some methods are also producing misleading error strings, this should be cleaned up while implementing Exceptions.

**Comment by rapha-dev** [comment]
Merged into `develop`.
