### ISSUE TITLE
IsConnected don't check if connection setup is done (Open())

### ISSUE THREAD

**Issue by rapha-dev** [S7NetPlus/s7netplus#154]
As title says, running a `Read` (or any read/write action) without prior `Open` will throw a `TPKTInvalidException`.
`IsConnected` should check actual connection by sending a empty PDU (as mentioned in source already).

This behavior breaks old implementations where `IsConnected` actually checks for prior `Open` (before 0.1.8).

**Comment by mycroes** [comment]
The IsConnected property of `PLC` now reflects the `IsConnected` state of the underlying `TcpClient`. #349 will actually add to that by having the connection closed on errors.

**Comment by mycroes** [comment]
Also see #523, I tink this can be closed now.
