### ISSUE TITLE
Incorrect String handling with vartyp StringEX 

### ISSUE THREAD

**Issue by bauerju** [S7NetPlus/s7netplus#159]
Hi. Writing a string over a daitem, declared as StringEX,  doesn't work. 

The first two bytes in then memory, which represents declared and used length are overwriten.  
Simple Code:
![2018-07-09 07_54_40-flsng - microsoft visual studio](https://user-images.githubusercontent.com/40683441/42432943-5dc806fa-834d-11e8-9cbc-77d0d8c0be63.png)

DB before writing:
![2018-07-09 07_43_25-clipboard](https://user-images.githubusercontent.com/40683441/42432899-24deec32-834d-11e8-9831-b88ecc368852.png)

DB after writing:
![2018-07-09 07_45_11-s7 watch](https://user-images.githubusercontent.com/40683441/42432921-40ee6600-834d-11e8-804c-6db5ebfd9389.png)

Jürgen

**Comment by mycroes** [comment]
I believe the current code doesn't check the vartype when writing. I'll try to fix it this evening.

**Comment by bauerju** [comment]
Hi @mycroes 
Yes you'r right. I digged a bit into the code. There is no check for  the vartype. 

Jürgen

**Comment by mycroes** [comment]
@bauerju / Jürgen thanks very much for your feedback, address this issue in PR #162. I'm very happy with the way you provide feedback, so please keep it coming.
