### ISSUE TITLE
Incorrect String handling with VarType.String 

### ISSUE THREAD

**Issue by bauerju** [S7NetPlus/s7netplus#164]
Writing VarType.String doesn't care about the length of the string.:
![image](https://user-images.githubusercontent.com/40683441/42551073-a44d3c4c-84d5-11e8-915a-fa9540651754.png)

Plc.Write(da) writes full string length into the plc. 
![2018-07-11 06_41_22-s7 watch](https://user-images.githubusercontent.com/40683441/42551090-cd0d1382-84d5-11e8-9c1b-4eb71f99d063.png)

Plc.Read() cares about length and reads only correct length.
![2018-07-11 06_41_59-flsng debugging - microsoft visual studio](https://user-images.githubusercontent.com/40683441/42551115-f7e10d70-84d5-11e8-8590-14bf09e7ce98.png)

Jürgen

**Comment by bauerju** [comment]
HI
Writing a shorter string, which is shorter as defined, writes only string length.
eg. 
string in DB is defined as 8 bytes and value is `ABCDEFGH`
Reading gives correct  `ABCDEFGH`
Writing `0123` , 
string in DB is after write `0123EFGH`.
Should the rest not filled with \0 ? I Think it should be `0123\0\0\0\0`


Jürgen

**Comment by mycroes** [comment]
HI @bauerju. Agreed in full. I will change the implementation to write at most `count` bytes and to pad with `\0`.
