### ISSUE TITLE
TPKT error trying reading/writing merker value

### ISSUE THREAD

**Issue by aetasoul** [S7NetPlus/s7netplus#185]
Hi all,

I'm trying the c# library on visual studio 2017, I have installed it via nuget packages.
I'm getting this error when I run my application:

>TPKT is incomplete / invalid

The cpu is S7-300.

This is my code:
```
using S7.Net;

Plc plc = new Plc(CpuType.S7300,"192.168.1.1",0,2)
plc.Open();

if(plc.isConnected && plc.isAvailable){
    plc.Write("M20.0",true);
    bool testRead = (bool)plc.Read("M20.1");
}

plc.Close();
```

I'm getting the error on: plc.Write("M20.0",true) 

If I comment the line I get the error on the reading command.

On the PLC I have only the OB1 with one segment.

|-----|M20.0| -------(M20.1)---

Thanks for help!

**Comment by jerko1979** [comment]
Hi,
Maybe you should check your write permission on CPU settings?
good luck!
    četvrtak, 6. rujna 2018. 12:24:24 CEST, korisnik aetasoul <notifications@github.com> napisao je:  
 
 
Hi all,

I'm trying the c# library on visual studio 2017, I have installed it via nuget packages.
I'm getting this error when I run my application:


TPKT is incomplete / invalid


The cpu is S7-300.

This is my code:

using S7.Net;


Plc plc = new Plc(CpuType.S7300,"192.168.1.1",0,2)
plc.Open();

if(plc.isConnected && plc.isAvailable){
plc.Write("M20.0",true);
bool testRead = (bool)plc.Read("M20.1");
}

plc.Close();


I'm getting the error on: plc.Write("M20.0",true)

If I comment the line I get the error on the reading command.

On the PLC I have only the OB1 with one segment.

|-----|M20.0| -------(M20.1)---

Thanks for help!

**Comment by jerko1979** [comment]
Hi,
Maybe you should check your write permission on CPU settings?
good luck!

**Comment by jerko1979** [comment]
Also confirm that your CPU is mounted on Rack = slot 2 in HW coinfig?

**Comment by mycroes** [comment]
@aetasoul I'm not sure if anyone ever tested writing memory bits, if I look through the code it seems probable that it's broken (the vartype that is parsed from the address doesn't seem to be used anywhere). Can you verify that you have successful communication (read/write) in DB areas?

**Comment by aetasoul** [comment]
Hi,

This is my HW configuration:
![rack_slot](https://user-images.githubusercontent.com/15131692/45205176-b14dee80-b281-11e8-80e8-ff725c34ff0a.png)

And this is the DB1 that I create for test:
![db1](https://user-images.githubusercontent.com/15131692/45205205-c0cd3780-b281-11e8-9423-27c27502c1c9.png)

I have changed my code like this:

> using S7.Net;
> 
> Plc plc = new Plc(CpuType.S7300,"192.168.1.1",0,2)
> plc.Open();
> 
> if(plc.isConnected && plc.isAvailable){
> plc.Write("DB1.DBX2.0",1);
> bool testRead = (bool)plc.Read("DB1.DBX2.1");
> //plc.Write("M20.0",true);
> //bool testRead = (bool)plc.Read("M20.1");
> }
> 
> plc.Close();

the error is the same:

> TPKT is incomplete / invalid

@jerko1979 the racks and slot are right as yo ucan check in the picture. What do you mean with "Maybe you should check your write permission on CPU settings?"?

@mycroes I have checked this example for start: https://archive.codeplex.com/?p=s7net

Thanks for help guys!

**Comment by jerko1979** [comment]
![image](https://user-images.githubusercontent.com/37616873/45206570-95e4e280-b285-11e8-9a71-51d9ed2e41ab.png)

**Comment by jerko1979** [comment]
![image](https://user-images.githubusercontent.com/37616873/45206661-db091480-b285-11e8-9770-cf7868ab1406.png)

**Comment by jerko1979** [comment]
![image](https://user-images.githubusercontent.com/37616873/45206737-0986ef80-b286-11e8-8b50-ae754eede5e8.png)

**Comment by aetasoul** [comment]
I have only the keyswitch settings checked.

No protection

![protezione](https://user-images.githubusercontent.com/15131692/45206896-929e2680-b286-11e8-96a9-c290244eed97.png)

**Comment by aetasoul** [comment]
This is the project, just dearchive it.
If you want you can take a look!

[Testcommunication.zip](https://github.com/S7NetPlus/s7netplus/files/2360194/Testcommunication.zip)

Thanks!

**Comment by mycroes** [comment]
@aetasoul  I think you might have an error in the `Write` call, I think you need to pass a `bool` instead of `1`, although I'm 100% confident it's a problem.

```csharp
plc.Write("DB1.DBX2.0", true);
bool testRead = (bool)plc.Read("DB1.DBX2.0");
}
```

Could you perhaps try to read just an int or dint? Also, make sure the exception is originating from the `Read` or `Write` calls, there have been issues with opening connection as well with some PLC's.

**Comment by mycroes** [comment]
> Maybe you should use sharp7 , library here is the link how to . I have never uset s7net to be honest!
https://www.mesta-automation.com/how-to-write-a-siemens-s7-plc-driver-with-c-and-sharp7/

@jerko1979 I don't think you're really helping @aetasoul by pointing him to another library (where I'm afraid the support will be far worse than here, since the developer is a C programmer that ported his code to C# following C conventions). You provided some good advice with regards to the settings, we should be able to get this problem solved by diagnosing what's going on.

**Comment by aetasoul** [comment]
I found the problem.

> using S7.Net;
> 
> Plc plc = new Plc(CpuType.S7300,"192.168.1.1",0,2)
> plc.Open();
> 
> if(plc.isConnected && plc.isAvailable){
> plc.Write("M20.0",true);
> bool testRead = (bool)plc.Read("M20.1");
> }
> 
> plc.Close();

on this code if I remove the "if" statement for check if the plc.IsAvaiable && plc.IsConnected  can write the memory bit 20.0 and read from the memory bit 20.1

the working code is this:

> Plc plc = new Plc(CpuType.S7300,"192.168.1.1",0,2);
> plc.Open();
>
> plc.Write("M20.0",true);
> bool testRead = Convert.ToBoolean(plc.Read("M20.1"));
> 
> plc.Close();

**Comment by jerko1979** [comment]
Well Done ! 👍

**Comment by aetasoul** [comment]
It also works for DB. 
So you can read/write memory bit and DB.

Thanks all for the help!

If you need any help to test the library, or improve it tell me. I'm interested in it and I have this cpu: 315-2 PN/DP, 315-2 DP, S7-1500, S7-1200, ET200SP, s7-314, 316-2 DP, 317-2 DP

**Comment by jerko1979** [comment]
I guess methods: IsAvailable&&IsConnected  are not complete :
public bool IsAvailable
        {
            //TODO: Fix This
            get
            {
                    return Connect() == ErrorCode.NoError;                   
            }
        }

        /// <summary>
        /// Checks if the socket is connected and polls the other peer (the PLC) to see if it's connected.
        /// This is the variable that you should continously check to see if the communication is working
        /// See also: http://stackoverflow.com/questions/2661764/how-to-check-if-a-socket-is-connected-disconnected-in-c
        /// </summary>
        public bool IsConnected
        {
            get
            {
                try
                {
                    if (tcpClient == null)
                        return false;

                    //TODO: Actually check communication by sending an empty TPDU
                    return tcpClient.Connected;
                }
                catch { return false; }
            }
        }

**Comment by mycroes** [comment]
@aetasoul @jerko1979 Thanks to both of you. The `IsAvailable` method has been broken in recent versions, I'll make sure a separate issue covers this.

**Comment by Alkaidxx** [comment]
how do you fanilly solve it? what's main problem, is s7.net or plc set wrong?
