### ISSUE TITLE
Bug on 0.7 bit while using asynchronous write method

### ISSUE THREAD

**Issue by Candogru** [S7NetPlus/s7netplus#201]
I am developing a windows form with asynchronous methods. The below code write true or false at first 7 bit of DB as 0.0, 0.1....0.6
But when I try to write true at 0.7, nothing chance on the face of PLC (it means it is already false on PLC). It doesn't throw any exception on Visual Studio so that means the code wrote true to that tag.
When I chance the adress of that tag to 1.0 or 1.1, on the PLC it seems true as the code wrote.

By the way I don't force to false on PLC

`
 private bool PLCBoolVeriYaz(string DB_Adress, bool statusOfTag)
        {
            bool successful= false;
            try
            {
                Task.Run(async () => { await baglanPLC.WriteAsync(DB_Adress, Convert.ToBoolean(statusOfTag)); }).Wait();
                successful= true;
            }
            catch (Exception)
            {

            }
            return successful;
        }
`

**Comment by mycroes** [comment]
Please try with S7NetPlus 0.4.0 and see if it's fixed there.
