### ISSUE TITLE
Version 0.3.0 (IsConnected) usage

### ISSUE THREAD

**Issue by StarRainFox** [S7NetPlus/s7netplus#209]
Hello, I found a problem when using the version 0.3.0. The problem is that the property (IsConnected) of the object is always (true) in (New PLC), so I don't know when to use (Open) method and (Close) method.

**Comment by mycroes** [comment]
Hi @StarRainFox,

This is a known issue. Join in on the discussion on #154 if you have something to add. For now, I'll close this as duplicate.
