### ISSUE TITLE
PLC.Close Method doesn't diconnect PLC 

### ISSUE THREAD

**Issue by EFikir** [S7NetPlus/s7netplus#211]
Hello,

When I try to diconnect plc by using PLC.Close() method, I realize that PLC is also connected after this method by checking PLC.IsConnected (it returns true)

Thanks in advance

**Comment by mycroes** [comment]
Hi @EFikir,

Unfortunately the IsConnected property has been stubbed to return true (exact reason unknown to me), so the error is only with that property. The connection will actually be closed on `plc.Close()`.
