### ISSUE TITLE
S7.Net.Types.Boolean.ClearBit() not working

### ISSUE THREAD

**Issue by MarcOnFire** [S7NetPlus/s7netplus#214]
Hi,
I'm not sure 100% but it seems that ClearBit is not clearing bit, actually I'm using a custom function with:
    `return (byte)(value & (~(1 << bit)));`
instead of 
    `return (byte)((value | (~(1 << bit))) & 0xFF);`

Thanks a lot for all your work on this library.

**Comment by mycroes** [comment]
This should be fixed now. I feel stupid for missing this issue report as I had to run into this myself as well....
