### ISSUE TITLE
Sometimes Value is not written to DB

### ISSUE THREAD

**Issue by tomaskrutak** [S7NetPlus/s7netplus#215]
Hi,
I am connected to PLC and writing to DB using method :
_S7Plc.Write("DB100.DBW0", 1);

Write function works most of the time but once in around 6 write attempts write fails. So DB value is not changed.
Do I miss some PLC setting or what can be reason?
Thank you
Tomas Krutak

**Comment by mycroes** [comment]
Hi @tomaskrutak,

I have experienced similar issues on multiple occassions (with Sally7 and Siemens' own SAPI-S7, I don't actually use S7NetPlus myself). There is some datablock property specifying data direction. I believe by default it's set to in/out, which causes this issue. I'm sorry this is a bit vague, I'm not a PLC programmer. Let me know if you can find the setting, otherwise I can ask the PLC programmers at my company.

**Comment by tomaskrutak** [comment]
Hello,
Thank you, but Im not aware there is such setting on shared DB if its in or out...
______________________________________________________________
> Od: "Michael Croes" <notifications@github.com>
> Komu: "S7NetPlus/s7netplus" <s7netplus@noreply.github.com>
> Datum: 17.05.2019 21:53
> Předmět: Re: [S7NetPlus/s7netplus] Sometimes Value is not written to DB (#215)
>
Hi @tomaskrutak <https://github.com/tomaskrutak>,
I have experienced similar issues on multiple occassions (with Sally7 and Siemens' own SAPI-S7, I don't actually use S7NetPlus myself). There is some datablock property specifying data direction. I believe by default it's set to in/out, which causes this issue. I'm sorry this is a bit vague, I'm not a PLC programmer. Let me know if you can find the setting, otherwise I can ask the PLC programmers at my company.

**Comment by mycroes** [comment]
Hi @tomaskrutak,

In the attached image you can see variable *IN1* and *IN2* declared specifically as *Input*. If they would have been declared as *InOut* that often results in the written values not received in the PLC.

Regards,
Michael

![image](https://user-images.githubusercontent.com/122017/58021487-4bea1700-7b0b-11e9-981d-07838bc46a2a.png)

**Comment by mycroes** [comment]
Closing due to missing response. Feel free to reopen if the issue persists.
