### ISSUE TITLE
Add ReadTimeout and WriteTimeout

### ISSUE THREAD

**Issue by ChipsetSV** [S7NetPlus/s7netplus#217]
Hello.

I use S7.Net library in synchronous mode. Connection between app and PLC is very bad and often it lose. Sometimes socket is starting read and cannot wait end of it (hangs). I want to control this situations by set ReadTimeout and WriteTimeout for Socket or NetworkStream. Now TcpClient and NetworkStream are private and I cannot set these paramerers for connection to PLC.

Can you add the ability to set ReadTimeout and WriteTimeout?

**Comment by ChipsetSV** [comment]
#218

**Comment by mycroes** [comment]
Thanks for creating the PR. As mentioned there, this is a good addition to the API.
