### ISSUE TITLE
Problems reading merker bit

### ISSUE THREAD

**Issue by YastrebovV** [S7NetPlus/s7netplus#232]
Hello to all! I found a small bug)
It was: `  case "M":
                                // Memory
                                dataType = DataType.Memory;
                                varType = VarType.Byte;
                                break;`

Fixed: `  case "M":
                                // Memory
                                dataType = DataType.Memory;
                                varType = VarType.Bit;
                                break;`

**Comment by allibragi** [comment]
Hi @YastrebovV, i think you should submit a pull request with the bugfix. 
It's easer for the devs to check it and put it in the official release.

**Comment by mycroes** [comment]
Has been fixed for quite a while, closing.
