### ISSUE TITLE
COM interop

### ISSUE THREAD

**Issue by elisabetta2016** [S7NetPlus/s7netplus#241]
Is it possibile to do an enabled COM Interop built to be able to interface it via Excel vba?
Thanks

**Comment by mycroes** [comment]
Hi @elisabetta2016,

Not sure if you were still expecting an answer, but no, I won't add COM interop to S7NetPlus. I don't think it's well-suited for COM interop, you could however just write your own wrapper and expose that.

Regards,
Michael
