### ISSUE TITLE
 S7 v 0.4.0  has no error processing

### ISSUE THREAD

**Issue by dimafainberg** [S7NetPlus/s7netplus#243]
in v 0.4.0  has no error processing(var result = plc.Open();),      plc. Open return void  
  cant be equal to var.. can you help PLZ  thnaks!!

**Comment by timverwaal** [comment]
I had the same issue. The solution however is simple. 
The `Open()` method throws an exception when something goes wrong.

```
using (var plc = new Plc(CpuType.S71500, "192.168.0.1", 0, 1))
{
    try
    {
        plc.Open();

    } catch (Exception e)
    {
        // This code is only executed when something went wrong with Open();
        Console.WriteLine(e.Message);
    }           	
}
```

**Comment by dimafainberg** [comment]
Thank you !! But if a problem with read ? in previous version was a LastErrorCode

**Comment by timverwaal** [comment]
This works the same. I looked up the commit for this change: https://github.com/S7NetPlus/s7netplus/commit/1538de148b4aa48f845f14181cfa4ad5cd7ccbf2 (_"Replace LastErrorCode and LastErrorString with exceptions"_)

**Comment by dimafainberg** [comment]
Thanks now i see !!!!

**Comment by mycroes** [comment]
Closing, feel free to reopen if you're still running into problems with how this changed (`LastErrorCode` vs Exceptions).
