### ISSUE TITLE
S7-1212C Can't read data.

### ISSUE THREAD

**Issue by WontheMikeLi** [S7NetPlus/s7netplus#248]
The exception is "Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host."

Version 3.0 also has the same exception.
Sample code is below

            try
            {
                if (objTemp_Plc.IsConnected)
                {
                    //byte[] readByte = objTemp_Plc.ReadBytes(DataType.DataBlock, 1, 0, 1);
                    object objTemp = objTemp_Plc.Read(DataType.DataBlock, 1, 0, VarType.Byte, 1);
                    //object uscita = objTemp_Plc.Read("DB1.DBB0");
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }

Sharp 7 can read data.

**Comment by mycroes** [comment]
Can you try without plc.IsConnected? I believe that's still bugged (i.e., destroying the connection).

**Comment by WontheMikeLi** [comment]
Thanks a lot, as what you said, after comment plc.IsConnected it works like a charm.
