### ISSUE TITLE
Read IW

### ISSUE THREAD

**Issue by sudak-91** [S7NetPlus/s7netplus#251]
Hello. How i can read analog input?

**Comment by Mallowan** [comment]
Hello,
the handling with analog plc inputs supposes to have respective analog modules. Do you agree?
Then the having of onboard analog modules provides an opportunity to digitize your analog signal.
Correspondingly the digitized signal you can pass whenever you want nowadays. Even with this library.

hope this helps.

**Comment by sudak-91** [comment]
Can i use PLC.Read("IW20")?

пн, 20 янв. 2020 г. в 11:45, Mallowan <notifications@github.com>:

**Comment by Mallowan** [comment]
first, you have to pass that input word to the word which is located in Global DB, then read it from there.

**Comment by sudak-91** [comment]
I can read this signal from DB, because i forgot switch off  db
optimisation.

пн, 20 янв. 2020 г. в 11:50, Mallowan <notifications@github.com>:

**Comment by FalcoGoodbody** [comment]
Can you turn the optimization off? You just need to do this for the DB you want to read from.

**Comment by mycroes** [comment]
@sudak-91 I think you can now read IW20, can you test this on 0.7.0?

**Comment by mycroes** [comment]
Should've been fixed for a while now, closing. Feel free to reopen if there's still issues reading IW.
