### ISSUE TITLE
Unable to read PLC DB data

### ISSUE THREAD

**Issue by 05749** [S7NetPlus/s7netplus#252]
Hi, I am using the S7-1200 and TIA portal V1.4.
I am running Readbytes from the S7.net library, but I get the following error:
 "Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host."
I can do plc.open () and plc.close () without any problems.
Is there any solution? Any advice is welcome.
thank you in advance.
![plc program](https://user-images.githubusercontent.com/60371927/73341639-6393b500-42c0-11ea-96a3-a3b7a6bcc725.png)

**Comment by FalcoGoodbody** [comment]
Did you check that the DB is not optimized?

**Comment by 05749** [comment]
Thank you for your comment.
Yes, I unchecked DB optimization according to the documentation.
![image](https://user-images.githubusercontent.com/60371927/73581158-a8d80280-44cb-11ea-8599-6a426cbd7ad2.png)
Do I need other settings on the PLC besides the contents of this document?
Thank you.

**Comment by allatrue** [comment]
Did you enabled PUT/GET communication for the CPU?

**Comment by 05749** [comment]
Yes, I have enabled PUT / GET communication for the CPU .

**Comment by mycroes** [comment]
Try to remove the Plc.Isconnected check, it's broken.

**Comment by 05749** [comment]
I thought Plc.Isconnected was a way to verify communication with the PLC, but does it affect Plc.ReadBytes?

**Comment by mycroes** [comment]
I believe it accidentally terminates the connection. I'm way behind on fixing issues like this, because obviously this shouldn't be the case. Let me know if it works without the IsConnected check.

**Comment by 05749** [comment]
Thank you for your comment.
I was able to read the DB by removing the IsConnected check.
![Improved PLC program](https://user-images.githubusercontent.com/60371927/73617752-65190080-4665-11ea-952a-20f2dcf794a6.png)
thank you very much.

**Comment by FalcoGoodbody** [comment]
Well...that´s strange.
I am using the PLC.IsConnected to read data from a S7-1500 at there it works fine so far.
Maybe it is problem depending to the PLC used?

**Comment by mycroes** [comment]
Maybe one of you isn't using the latest version?

**Comment by FalcoGoodbody** [comment]
I´m using Version 0.4.0 from the last year. Via NuGet there is no newer one available.
For me everything works fine and I am absolutely happy with this library.

**Comment by 05749** [comment]
I using the same S7.Net version 0.4.0.
However, the PLC I'm using is S7-1200 and the CPU firmware version is V4.1.
Do these conditions affect anything?

**Comment by mycroes** [comment]
0.7.0 has some major improvements and better exception message on errors, so please retest.

**Comment by mycroes** [comment]
Closing, feel free to reopen if the issue persists.
