### ISSUE TITLE
Cant read or write in 0.4.0 s71200 tia portal v14

### ISSUE THREAD

**Issue by yusuflars** [S7NetPlus/s7netplus#257]
![Screenshot_1](https://user-images.githubusercontent.com/61707883/75705232-09757d80-5ccc-
![Screenshot_1](https://user-images.githubusercontent.com/61707883/75705379-49d4fb80-5ccc-11ea-8543-6d531710f0aa.png)
![Screenshot_2](https://user-images.githubusercontent.com/61707883/75705380-4a6d9200-5ccc-11ea-8f02-c34ab736a774.png)

11ea-9b26-2e14e0685cad.png)
![Screenshot_7](https://user-images.githubusercontent.com/61707883/75705234-0aa6aa80-5ccc-11ea-8cbf-a81e6fa211ac.png)
![Screenshot_7](https://user-images.githubusercontent.com/61707883/75705378-49d4fb80-5ccc-11ea-81cd-ee445337d99e.png)

![Screenshot_3](https://user-images.githubusercontent.com/61707883/75705375-493c6500-5ccc-11ea-9013-3a2dc9e0ca26.png)

Always getting "IndexOutOfRangeException"

**Comment by zoltraks** [comment]
This might be cause by not having "Protection & Security" option "Permit access with PUT/GET communication from remote partner" checked.

I have also put a Pull Request with small fix for that:

https://github.com/S7NetPlus/s7netplus/pull/258

**Comment by mycroes** [comment]
Closing, feel free to reopen if the issue persists.
