### ISSUE TITLE
TKPT error after initial connection success

### ISSUE THREAD

**Issue by MikeK-10** [S7NetPlus/s7netplus#262]
Addition to issue discussed #250 and new issue as requested. 

I am not using plcsim - I have an actual S7-1200 connected

**Comment by ccaiwl** [comment]
遇到同样问题  不定时的出现异常   真机s7-200 smart

**Comment by mycroes** [comment]
Hi @MikeK-10, can you retest against 0.7.0?

**Comment by MikeK-10** [comment]
Hi, still get the failures, error message now is:
"Couldn't establish the connection to 192.168.1.20. 
Message: TPKT header is incomplete / invalid. Received Bytes: 0 expected:4"

Restarting the project allows successful re-connection for a short period (30s to 1min)

**Comment by mycroes** [comment]
Hi @MikeK-10, perhaps it's a good idea to retry with 0.12.0. I've now implemented synchronization in the library, which is something that was really missing for a lot of people. Not sure if your issue relates to that, but if it's still not fixed then I'll remove the retest label and we can see what we can try next.

**Comment by mycroes** [comment]
Closing, feel free to reopen if the issue persists.
