### ISSUE TITLE
The relationship with PROFINET

### ISSUE THREAD

**Issue by mytion7** [S7NetPlus/s7netplus#264]
I tried to communicate with siemens plc through PROFINET.

I found this library, but I'm not sure this library support PROFINET or not.

If I use this library, can I says that my program communicates with PLC through PROFINET?

**Comment by RoyHeerkens** [comment]
The library uses s7 protocol, this is a different protocol than Profinet.

**Comment by mycroes** [comment]
@RoyHeerkens thanks for answering, to be honest I don't have much PLC experience, so I'm not sure about the internals of the Profinet protocol. S7NetPlus does indeed use the S7 protocol, which seems to be a proprietary Siemens protocol with almost no documentation.

**Comment by mycroes** [comment]
Let's answer this properly now. S7 and Profinet are entirely different. There are libraries available for Profinet communication and there are vendors that sell dedicated hardware for Profinet. Perhaps the latter also support the S7 protocol in some cases, but the protocols don't share any technical details.
