### ISSUE TITLE
No ErrorCode return for open() method 

### ISSUE THREAD

**Issue by gestepp** [S7NetPlus/s7netplus#268]
Hello,
The documentation mentions that the open () method has a return value from the ErrorCode enum. The last downloaded version, however, simply returns a void ... accordingly, I cannot evaluate the connection using the Enum ErrorCode.
Can anyone help me here?

I use VisualStudio 2019 Community!

Do I need a different version? Do I have to change anything? Do I get it any differently?

Thank you!

**Comment by mycroes** [comment]
Hi @gestepp,

Instead of returning an error (which is not the recommend way for error handling in C#) the `Open` method will now throw exceptions in case errors occur.

Regards,
Michael
