### ISSUE TITLE
plc.Read(string) function doesn't work when read memory bit (M0.0)

### ISSUE THREAD

**Issue by ZombieAllen** [S7NetPlus/s7netplus#270]

**Comment by ZombieAllen** [comment]
There's a fault in PLCAddress.cs. 

 case "M":
                            // Memory
                            dataType = DataType.Memory;
                            varType = VarType.Byte;
                            break;

the varType should be VarType.Bit.

**Comment by timverwaal** [comment]
I created a pull request for this: #246. Would this commit solve your problem?

**Comment by ZombieAllen** [comment]
> I created a pull request for this: #246. Would this commit solve your problem?

Hi , Thanks for your information. It works. I met a fault after compling.

Unable to locate the repository that contains the directory'E:\PersonalProject\Ref\s7netplus-PLCAdddres-Parsing\S7.Net'. S7.Net C:\Users\Administrator\.nuget\packages\microsoft.build.tasks.git\1.0.0-beta-62925-02\build\Microsoft.Build.Tasks.Git.targets 20

If you know something about it. Thanks in advance

**Comment by timverwaal** [comment]
Seems to me this unrelated to the issue. Something with git and/or Nuget that causes the fault.

**Comment by ZombieAllen** [comment]
> Seems to me this unrelated to the issue. Something with git and/or Nuget that causes the fault.

Thanks Mate

**Comment by mycroes** [comment]
@ZombieAllen I ran into the same issue when updating the build infra, but that should be fixed. Also, @timverwaal's PR is merged, so I'm closing this issue. Feel free to reopen if you still run into issues.
