### ISSUE TITLE
First time wanted to write entire class and happens nothing. 

### ISSUE THREAD

**Issue by Mallowan** [S7NetPlus/s7netplus#272]
Hello everyone,
First time I decided to write a class.

Class itself:

 ```
 public class Test
    {
        public int Value0 { get; set; }
        public int Value1 { get; set; }
        public int Value2 { get; set; }       
    }
```

Button event:

```
 private void Load_button_Click(object sender, RoutedEventArgs e)
        {

            Test  _test = new test();
            _test.Value0 = 33;
            _test.Value1 = 34;
       
           _service.plc.WriteClass(_test, 113, 0);
                  
        }
```
There are no any changes in DB113. There are no any exceptions in project.
What I'm doing wrong?
Any insights on this matter, please.

**Comment by FalcoGoodbody** [comment]
Did you open the connection first?
Can you show the structure of the DB113?

**Comment by Mallowan** [comment]
![DB114](https://user-images.githubusercontent.com/37699980/86920179-0a169880-c132-11ea-82b9-a54fc85f3af5.png)

**Comment by FalcoGoodbody** [comment]
I think you need convert the C#-INT into the S7-INT. Or you change the S7 into DINT.
It is described in the pdf-docu at the very end.

I think that is the problem. 
I myself haven´t yet tested to write a class, sorry.

**Comment by Mallowan** [comment]
@FalcoGoodbody , 
it started working when I doubled quantity of bits on the S7 side. Int --> DInt.
Since there was no a parity between C and  S7  integers.
Making _shorts_ on the side of C came to nothing. Not many made attempts, though.
Thanks a lot! It was very valuable advice.

**Comment by mycroes** [comment]
Hi @Mallowan, Can I close this issue? If not, can you provide a minimal sample that fails?
