### ISSUE TITLE
"TPKTInvalidException: TPKT is incomplete / invalid"

### ISSUE THREAD

**Issue by ccaiwl** [S7NetPlus/s7netplus#273]
"TPKTInvalidException: TPKT is incomplete / invalid"

**Comment by mycroes** [comment]
Please retest using 0.7.0. If it doesn't fix your issue, the exception might provide more detail with regards to what is going wrong.

**Comment by mycroes** [comment]
Closing, as this issue lacks any detail. Feel free to reopen if the issue persists with S7NetPlus 0.12.0.
