### ISSUE TITLE
Unable to use Plc.Read(DataType,startByte,varType,varCount)

### ISSUE THREAD

**Issue by ghost** [S7NetPlus/s7netplus#274]
If I try to read from DataBlock that only contains a single 16-bit integer. The read fails.
If i add another 16-bit integer after this one it works.
The error message is "WrongNumberReceivedBytes".

It seems that the socket connection always reads 4 bytes. 
Does anyone know a fix for this?

The code for this project is based on S7.Net 0.1.9, but I have also tried with 0.4.0, and both versions provide the same error message.

![Datablock fail](https://user-images.githubusercontent.com/57573795/87069479-8afb9000-c217-11ea-950b-1088ad9cac1c.png)
![Datablock ok](https://user-images.githubusercontent.com/57573795/87069483-8b942680-c217-11ea-9690-eb2aeb24d1cc.png)
![plcCode](https://user-images.githubusercontent.com/57573795/87069484-8b942680-c217-11ea-97da-11cde08534fe.png)

**Comment by mycroes** [comment]
Can you retest this against latest S7NetPlus (0.7.0)? It should at least provide a better exception message if it still fails.

**Comment by SmackyPappelroy** [comment]
It works in 0.7.0! So this issue is resolved

tis 8 sep. 2020 kl. 22:28 skrev Michael Croes <notifications@github.com>:

**Comment by mycroes** [comment]
Thanks for testing!
