### ISSUE TITLE
I can read a variable but I can't write

### ISSUE THREAD

**Issue by michaelsequeira86** [S7NetPlus/s7netplus#276]
I trying to write a variable in a S7-300.
The read method works.

bool example:
S7.NetSiemensS7Client.Write("DB216.DBX202.0", true);

I tried bool, int, word... but nothing is write into PLC

Protection;
![image](https://user-images.githubusercontent.com/67459241/88256650-20892c00-ccbc-11ea-985f-5c296e6c369f.png)

How can i check the errors when i write something, when all the write methods return void??

**Comment by FalcoGoodbody** [comment]
First please check if you have set the protection-level at the PLC to the lowest so that you can have full access as described on the last site in the pdf-documentation.

Second: I am using, for example, the following code write a single bit into a PLC

```cs
plc.WriteBit(DataType.DataBlock, 14, 0, 0, false);  
```

**Comment by michaelsequeira86** [comment]
> 
> 
> First please check if you have set the protection-level at the PLC to the lowest so that you can have full access as described on the last site in the pdf-documentation.
> 
> Second: I am using, for example, the following code to write a single bit into a PLC
> 
> ```cs
> private static Plc plc = new Plc(CpuType.S7300, "192.168.0.64", 0, 2);
> plc.Open();
> plc.WriteBit(DataType.DataBlock, 14, 0, 0, false);  
> plc.Clode();
> ```

I'm using Step7, the only protection I know is the parameter described above. Is not the same protection present in the pdf Document

I also tried to write with :
plc.WriteBit(DataType.DataBlock.........)
but nothing happened

**Comment by FalcoGoodbody** [comment]
Can you change this protection level to the radio-button "1 - key position"?
You need to upload hardware-configuration after you changed this.

**Comment by michaelsequeira86** [comment]
Thanks for your answer.
 The problem was that:

![image](https://user-images.githubusercontent.com/67459241/88364168-6e686780-cd82-11ea-8630-4d7c959cb961.png)

I increase the number of connections.... my bad

Thanks

**Comment by Paul8193** [comment]
> Thanks for your answer. The problem was that:
> 
> ![image](https://user-images.githubusercontent.com/67459241/88364168-6e686780-cd82-11ea-8630-4d7c959cb961.png)
> 
> I increase the number of connections.... my bad
> 
> Thanks

@michaelsequeira86 
I want to know whether the snapshot of PLC Communication Settings is correct for solve problem or not?  if not, would you please tell me how to increase the number of connections.  Thank you very much.
