### ISSUE TITLE
Dotnet Core 3.1 - Linux Issue

### ISSUE THREAD

**Issue by bressallg** [S7NetPlus/s7netplus#305]
I can't connect S7-1200 PLC when the program is running on Linux. No matter if the PLC exists or not in IP Address,
on Linux the error returns instantly.
Running the same project on Windows (console) works.
It seems that on Linux there is not a waiting time when you try to connect the PLC, while on Windows program it takes about 20s before return error, when there is no answer from the host.
Could you please help me to solve this issue?

**Comment by scamille** [comment]
Interesting..I haven't really tested this on Linux yet but should be easy to do.
Unfortunately the integration tests are windows only using a snap7 server.

Anyway:
- are you sind the synchronous Plc.Open().function?

I suspect this might be related to some timeout setting. There should be nothing special in S7NetPlus besides standard .Net Tcp client socket calls, so no particular reason to not work on Linux.

**Comment by scamille** [comment]
Try setting ReadTimeout = 0; and WriteTimeout = 0; before calling Open()

**Comment by scamille** [comment]
Added linux UnitTest and fixed Timeout problem in #306

**Comment by bressallg** [comment]
> Try setting ReadTimeout = 0; and WriteTimeout = 0; before calling Open()

Ok, working now! Thanks!
