### ISSUE TITLE
Improve Feedback when reading unavailable DB or reading too many bytes

### ISSUE THREAD

**Issue by scamille** [S7NetPlus/s7netplus#310]
When reading a DataBlock from the PLC that does not exist, or more bytes than exist in that DB, the error message is quite cryptic.

The idea is to figure out where/how in the S7 protocol such failures are communicated and turn that into a better Exception message.

**Comment by scamille** [comment]
Reading a DB that does not exist gives me:
```"Invalid response from PLC: '32-03-00-00-00-00-00-02-00-04-00-00-04-01-0A-00-00-00'."```

**Comment by scamille** [comment]
Reading past the end:
```Invalid response from PLC: '32-03-00-00-00-00-00-02-00-04-00-00-04-01-05-00-00-00'.```

**Comment by scamille** [comment]
Current check in code is:
```
            if (s7Data[14] != 0xff)
                throw new PlcException(ErrorCode.ReadData,
                    $"Invalid response from PLC: '{BitConverter.ToString(s7Data)}'.");
```
So I think we can add a enum containing possible values for Byte 15 of the response data.
0xff would be OK
0x0A would be DB does not exist / not accessible
0x05 requests read too long.

And of course a bit more sophisticated logic to check that and give the appropriate error message.

**Comment by mycroes** [comment]
https://github.com/mycroes/Sally7/blob/develop/Sally7/Protocol/S7/ReadWriteErrorCode.cs 😉
