### ISSUE TITLE
wrong addressing when using Write() with single variable WORD or INT

### ISSUE THREAD

**Issue by FalcoGoodbody** [S7NetPlus/s7netplus#326]
I just testet to write a single value to a S7-1515-2 PN plc.
```csharp
myPLC.Write(DataType.DataBlock, 83, 146, 100);
```
and also tried
```csharp
myPLC.Write("DB83.DBW146", 111);
```
The value is always written into DB83.DBW148 instead of DB83.DBW146.

Update: I just created a new data block with only 2 variables. If the first one is an INT or a WORD `Write()` failse.
If the first one is a DINT or DWORD `Write()`works nearly.
I get an exception:
```
S7.Net.PlcException
  HResult=0x80131500
  Nachricht = PLC communication failed with error 'WrongNumberReceivedBytes'.
  Quelle = S7.Net
  Stapelüberwachung:
   bei S7.Net.Plc.WriteBytesWithASingleRequest(DataType dataType, Int32 db, Int32 startByteAdr, Byte[] value, Int32 dataOffset, Int32 count)
   bei S7.Net.Plc.WriteBytes(DataType dataType, Int32 db, Int32 startByteAdr, Byte[] value)
   bei S7.Net.Plc.Write(DataType dataType, Int32 db, Int32 startByteAdr, Object value, Int32 bitAdr)
   bei S7.Net.Plc.Write(String variable, Object value)
   bei S7NetPlus_Testproject.Program.Main(String[] args) in C:\Users\Robert.Oppel.OPL-NB-008\source\repos\S7NetPlus-Testproject\S7NetPlus-Testproject\Program.cs: Zeile370

Innere Ausnahme 1:
PlcException: PLC communication failed with error 'WrongNumberReceivedBytes'.
```

If I place another variable after the INT, the values are written into the plc but the INT is written 2 bytes later.

```csharp
myPLC.Write("DB85.DBD0", 555);
myPLC.Write("DB85.DBW4", 22);
```
![DB85](https://user-images.githubusercontent.com/22148745/93344895-81536180-f832-11ea-8712-fc851b6747a3.png)

**Comment by scamille** [comment]
I can't really understand your strange string-based addresses as a non-PLC programmer. (They are also not really documented, right?)

Can you write an example using the first version of Write that you have (```myPLC.Write(DataType.DataBlock, 83, 146, 100);```) which matches the displayed DataBlock?

**Comment by FalcoGoodbody** [comment]
My fault guys...sorry.
I was a little bit confused yesterday.
Everything works fine until you use the correct value conversion.
If you write `myPLC.Write("DB85.DBW4",22)` the 22 is interpreted as an C# INT which is a DInt in S7.
If you write `myPLC.Write("DB85.DBW4",varValue)` and varValue is a short everything is correct.

It is the same when using ´myPLC.Write(DataType.DataBlock, 83, 146, 100);´ The 100 is a C#-Int and therefore a S7-DInt.
Strongly recommendet to use variables instead of numbers. All this is already described in the docu but I was not able to read correctly. Sorry.

**Comment by scamille** [comment]
Maybe S7.NetPlus should validate that the var type with the type of the value before doing anything.

**Comment by FalcoGoodbody** [comment]
Maybe...would be a nice feature
