### ISSUE TITLE
Cant Read S71500

### ISSUE THREAD

**Issue by RubenFarfan08** [S7NetPlus/s7netplus#329]
hi,
i am testing with s71500

but when i read variables i cant
![image](https://user-images.githubusercontent.com/70863183/93629225-8ab50900-f9ad-11ea-8d6c-13f8c1c12dca.png)

![image](https://user-images.githubusercontent.com/70863183/93629313-b33d0300-f9ad-11ea-9131-39af119ec3f2.png)

![image](https://user-images.githubusercontent.com/70863183/93629483-01520680-f9ae-11ea-952d-2b5a5c57cbac.png)

and i use the guide for S71500
https://github.com/S7NetPlus/s7netplus/wiki/S7-1200-1500-Notes

but i cant read db.

please let me know if i'm coding wrong
Thanks

**Comment by FalcoGoodbody** [comment]
@RubenFarfan08 please check the also the conversion page in the documentation and read carefully the S7-1200-1500 notes. As I can see on your screenshot you are trying to read from an optimzed data block which is not supported by this library.
Please change the attributes to non-optimized, activate PUT/GET communication and set the access level to full. Follow then the docu and the conversion page.

If you might still have problems, don´t hesitate to ask for help here.

**Comment by FalcoGoodbody** [comment]
@RubenFarfan08 could you solve your problem? Does it work now?

**Comment by SmackyPappelroy** [comment]
@RubenFarfan08 Youre problem might be that your DB is optimized. Uncheck that tick-box in TIA portal and try again

**Comment by wangzhongkui** [comment]
Read(DataType, 78, 0, VarType.Dint,16,)
