### ISSUE TITLE
XML-comments when using Nuget package

### ISSUE THREAD

**Issue by SmackyPappelroy** [S7NetPlus/s7netplus#333]
Why am I not seeing the XML-comments when using the S7Net Nuget package?

**Comment by mycroes** [comment]
Because I failed to include it... Will add them when I have some spare time.

**Comment by SmackyPappelroy** [comment]
@mycroes I am glad to see a new version of S7.Net (0.8.0), but the XML-comments don't seem to be working in the Nuget-package in this version.

**Comment by mycroes** [comment]
Thanks for reminding, will try to make some more time this week so I can fix this as well. Let's leave this issue open until it's fixed 😉

**Comment by mycroes** [comment]
Hi @SmackyPappelroy, just released 0.8.1 which includes documentation. Should be live on NuGet already!
