### ISSUE TITLE
Connection with multiple PLCs

### ISSUE THREAD

**Issue by matteomezzanotte** [S7NetPlus/s7netplus#341]
Hi, I'm developing an application which should read and write data from multiple PLCs. Is it possible open several connections simultaneously? If not, what could be a solution? Thanks.

**Comment by SmackyPappelroy** [comment]
You can open as many connections as your PLC will allow! S7.Net uses the S7-Communication protocol

**Comment by matteomezzanotte** [comment]
Yes I know, but can I open many connections with more than one PLC ?

**Comment by SmackyPappelroy** [comment]
One connection per Plc object @matteomezzanotte

**Comment by matteomezzanotte** [comment]
So, through many Plc objects I can establish many connections with different Plcs

**Comment by SmackyPappelroy** [comment]
Exactly @matteomezzanotte
