### ISSUE TITLE
 I found some mistakes

### ISSUE THREAD

**Issue by OOOOO1** [S7NetPlus/s7netplus#348]
Using ReadStruct and ReadClass to read the data read by UInt32 is incorrect
![错误一(1)](https://user-images.githubusercontent.com/59185414/97865794-bc0f4b80-1d45-11eb-9608-708854ae6066.PNG)
![截图2](https://user-images.githubusercontent.com/59185414/97865808-c0d3ff80-1d45-11eb-8f78-99d1a2b8de46.PNG)

**Comment by FalcoGoodbody** [comment]
Hello @OOOOO1 ,

can you describe the mistake you think you have found a little bit more detailed?
I can not unterstand correctly from the pictures.
You do not use "ReadStruct" or "ReadClass" at all in the pictures...
