### ISSUE TITLE
value conversion

### ISSUE THREAD

**Issue by FeigelChina** [S7NetPlus/s7netplus#350]
how to read the address like DB2119.DD32?
From the Wiki, I don't find the related value conversion about "DD".
When I read the source code, it does not mention the situation in case of "DD". Look at the attached screenshort.

![image](https://user-images.githubusercontent.com/55540524/99744381-8ecae780-2b12-11eb-9f30-a9923fa701f7.png)

**Comment by FalcoGoodbody** [comment]
Hello @FeigelChina ,

what datatype in S7 should DD be?
A double word is DBD.

Can you show an example of the data you want to read?

**Comment by FeigelChina** [comment]
Hello @FalcoGoodbody  
The level 1 co-workers give me the wrong data address. They left out a letter "B".  There is no datatype in S7 should DD be. 
Thank you very much!
