### ISSUE TITLE
Can't read PLC DB Tag of "Array[0..2] of myDataType"

### ISSUE THREAD

**Issue by tadej-ihs** [S7NetPlus/s7netplus#354]
DB in TIA PORTAL
![image](https://user-images.githubusercontent.com/67745166/102086015-b8c4b080-3e17-11eb-80e0-fb2333a23115.png)

My Model object named TestDB3
---------------------
![image](https://user-images.githubusercontent.com/67745166/102090408-bd8c6300-3e1d-11eb-96a4-7376cabdd773.png)

Json result of ReadClass function
----------------
![image](https://user-images.githubusercontent.com/67745166/102090304-99c91d00-3e1d-11eb-9dc8-d8cc9bb76023.png)

Hi!

I'm trying to read values from DataBlock into Asp.Net Core 3.1 class. I'm using ReadClass\<T\> function to get data, where T is of type TestDB3.
It works fine reading from property named "one" to "twelve". Then at "thirteen" there is reading mismatch. At "fourteen" there is again everything as expected.

As a mismatch I have in mind that only "thirteen[0]" gets correct values for "c" and "d" property, then at "thirteen[1]" both properties "c" and "d" are left on default value regardles of being set to "true" on PLC DB side,

I have a feeling that I'm limited to tranfer only basic data types ( like property "one"-"ten"), array of basic data types (like property "eleven") and single custom data type ( like property "twelve" and "fourteen").

Can I transfer array of custom data type like i show with property "thirteen"?

If i'm doing something wrong, correct me please :) 

Thanks! 

Tadej

[Update] - I posted wrong pictures for TestDB4 ( missing "twelve" prop) and  Json result without "twelve"

**Comment by scamille** [comment]
Please try out using this as a replacement for you thirteen class:
```
public class thirteen
{
  public bool c {get;set;}
  public bool d {get;set;}
  public byte Dummy {get;set;}
}
```

My guess is that calculation of adresses is not correct in S7NetPlus, and it does not align correctly to the even adresses.

**Comment by tadej-ihs** [comment]
Hi! 

Your quess is correct. It now works fine. 

It means that "array[0..x] of bool" is inclined to mistakes correlated to addresses or better say "PLC offsets". With included " dummy" byte secound array item reads from right values.

Thanks a lot!

**Comment by scamille** [comment]
As far as I understand it, UDTs are always of an even size. So if you have a odd number of bytes in it (like you have with your 2 bools, which make up 1 byte), the size of the UDT is still 2 bytes and not 1.

Automatic calculation of this is probably something that should be added to S7NetPlus as a improvement. When something like this is implemented, the solution with the Dummy byte should still not break in any way since you are now already at a even size.
