### ISSUE TITLE
PLC out of range error

### ISSUE THREAD

**Issue by pierCartes** [S7NetPlus/s7netplus#389]
when reading an array of bit i get an out of range error i found that this line is retuning the wrong value i think that some ( ) are missing between "varCount + 7"

https://github.com/S7NetPlus/s7netplus/blob/d10c15b80f7a8fd9a393fae17690fdaf219dfc1d/S7.Net/PLCHelpers.cs#L187

**Comment by mycroes** [comment]
Thx @pierCartes! Fixed, will be included in next release.
