### ISSUE TITLE
Read incorrect value when I put a float variable in a struct

### ISSUE THREAD

**Issue by funnyYang1994** [S7NetPlus/s7netplus#430]
when I read a struct and write line a float type  variable, the value of that variable is "6.157642E-39" ,but the value in plc is "141.0".I  had searched document for long time ,but still have no idea. Could some one help me? 
Thank you very much!
![1](https://user-images.githubusercontent.com/102145219/159447502-fd621b37-de15-463b-88d5-0d565cc4e9e9.PNG)
![2](https://user-images.githubusercontent.com/102145219/159447710-b662dd7e-6920-45d5-93f6-9b023fba878e.PNG)

**Comment by mycroes** [comment]
Hi @funnyYang1994, Have you tried reading just a single value at the correct offset? My guess is the offset calculation in S7NetPlus is wrong, I would suggest trying to read the AxisConfig structs only starting at the correct offset. Please report back if that works.

The separate bits and bytes might be throwing off the calculation, I'm assuming that `testStruct` has 22 bytes for `codeHSG1`, 2 bytes for `spareBit1` to `spareBit3`, 2 bytes for `spareByte1` and `spareByte2` and so `oilAxisX` is starting at an offset of 28 within the struct. Can you confirm that as well?

**Comment by scamille** [comment]
My assumption would be that oilAxisX starts at offset 26, but S7NetPlus might calculate it to offset 25, because it does not correctly pad the last byte.
0 + 22 (string) + 2 (3x bool, 1x byte), + 2 (1x byte, 1x byte padding) = 26

**Comment by scamille** [comment]
Code example to test what @mycroes suggests:
`var oilAxisX = (AxisConfig)plc.ReadStruct(typeof(AxisConfig), 1750, 28);` or
`var oilAxisX = (AxisConfig)plc.ReadStruct(typeof(AxisConfig), 1750, 26);`

**Comment by mycroes** [comment]
> My assumption would be that oilAxisX starts at offset 26, but S7NetPlus might calculate it to offset 25, because it does not correctly pad the last byte. 0 + 22 (string) + 2 (3x bool, 1x byte), + 2 (1x byte, 1x byte padding) = 26

I miscalculated (26 is what I was aiming for), I'm not sure if the byte is added after bits without padding though.

**Comment by funnyYang1994** [comment]
> Hi @funnyYang1994, Have you tried reading just a single value at the correct offset? My guess is the offset calculation in S7NetPlus is wrong, I would suggest trying to read the AxisConfig structs only starting at the correct offset. Please report back if that works.
> 
> The separate bits and bytes might be throwing off the calculation, I'm assuming that `testStruct` has 22 bytes for `codeHSG1`, 2 bytes for `spareBit1` to `spareBit3`, 2 bytes for `spareByte1` and `spareByte2` and so `oilAxisX` is starting at an offset of 26 within the struct. Can you confirm that as well?

I check the size of the struct in plc , the wrong offset does cause this issue. The first image is the struct in plc ,I change the struct in C# program like the second picture , and now I can read value correctly. Thank you very much again!  
![3](https://user-images.githubusercontent.com/102145219/159608646-d5646a9e-f28d-40e1-ba8d-a682266981b3.PNG)
![4](https://user-images.githubusercontent.com/102145219/159608678-bceff5c8-fb02-4db3-8d0a-df71d2448532.PNG)
