### ISSUE TITLE
Problems when using extended ASCII codes (above number 127) in S7Strings

### ISSUE THREAD

**Issue by ismdiego** [S7NetPlus/s7netplus#436]
The default Encoding.ASCII used in S7String to serialize and deserialize strings to/from byte array is not always valid in some situations where you want to use extended ASCII Code Pages, like the Windows 1252, or Iso-8859-1.

I have created a PR (#435) with a proposed workaround for this, allowing the user to change the Encoding used by S7String system-wide. It only modifies S7String class, and the behavior is exactly the same if the user does nothing.

**Comment by mycroes** [comment]
Fixed in 0.14.0, thanks for the PR!
