### ISSUE TITLE
PLCSIM Advanced - Simulator Transfer error

### ISSUE THREAD

**Issue by paviano** [S7NetPlus/s7netplus#461]
Hi,
I want to report that apperently Read/Write doesn't work while working on PLC SIM Advanced V4.

Connection is established/disposed correctly.

The PLC in use is S1500, correcly run on physical one.  Down below a screenshot of exception:

![image](https://user-images.githubusercontent.com/59799846/212365845-06df17e9-fc2a-4067-895e-df418a53fd18.png)

Any suggestion?

**Comment by jiriurban21** [comment]
Check, if you have this option checked in PLC hardware configuration. 

![image](https://user-images.githubusercontent.com/76837530/226301692-5ea3f4be-202c-4768-83cd-4c7d2ee9c7dc.png)

**Comment by paviano** [comment]
Yes, it is

**Comment by mycroes** [comment]
@paviano could you add the solution, so if someone else runs into the problem they know how to fix it?

@jiriurban21 thanks for chiming in!
