### ISSUE TITLE
DInt.FromByteArray(byte[] bytes) may be got wrong value in Big-Endian PC

### ISSUE THREAD

**Issue by weiwxg** [S7NetPlus/s7netplus#465]
As i saw method `ReadMultipleVars()` read bytes from plc and parse to `Int32` use this method:
```
public static Int32 FromByteArray(byte[] bytes)
{
    if (bytes.Length != 4)
    {
        throw new ArgumentException("Wrong number of bytes. Bytes array must contain 4 bytes.");
    }
    return bytes[0] << 24 | bytes[1] << 16 | bytes[2] << 8 | bytes[3];
}
```

it works correct now because of most of pc are Little-Endian device. Is it works for Large-Endian pc?

**Comment by scamille** [comment]
I am pretty sure the assumption is that S7NetPlus. only works on little endian computers. That might not be true for all platforms that .NET runs on, but it is unlikely that these more esoteric ones will be used for running S7NetPlus.
