### ISSUE TITLE
Choose license ? 

### ISSUE THREAD

**Issue by kbeaugrand** [S7NetPlus/s7netplus#466]
I would like to use this library inside an Open Source product, but I need to clarify first under which license I can use your library. 

My product is under MIT license.

Can you define the type of OpenSource license of this library? 

Thanks in advance,

**Comment by killnine** [comment]
This projects license.txt is available in the main directory and is under the MIT license.

**Comment by kbeaugrand** [comment]
My bad, I didn't get it... Many thanks
