### ISSUE TITLE
Full duplex communication support

### ISSUE THREAD

**Issue by nguyenvanvy1999** [S7NetPlus/s7netplus#473]
Hello developer team. I have a question, can you give me a answer:
- Is this library support full duplex communication.
Thanks

**Comment by mycroes** [comment]
What do you mean by _full duplex_?

**Comment by nguyenvanvy1999** [comment]
I mean can we write data and read data in the same time?

**Comment by mycroes** [comment]
Yes, although #467 indicates there might be an open issue with regards to concurrency. Please report back in #467 if you do run into any issues when reading and writing at the same time.
