### ISSUE TITLE
Add overloads taking (ReadOnly)Memory<byte>/Span<byte> arguments

### ISSUE THREAD

**Issue by ArgusMagnus** [S7NetPlus/s7netplus#481]
It would be great to have overloads of the `ReadBytes`/`WriteBytes` methods and their async counterparts which take `Span<byte>` and the like as arguments. This would enable us to read/write array slices.

If this is something you would accept, I may be able to provide a pull request for this.

**Comment by mycroes** [comment]
I'm definitely open to accepting those. Feel free to submit a PR when you're up to it.

**Comment by ArgusMagnus** [comment]
I created the pull request #482

**Comment by mycroes** [comment]
Fixed by #482, released as part of v0.17.0.
