### ISSUE TITLE
Is there any way to access the optimized DB blocks (symbolically)???

### ISSUE THREAD

**Issue by Crostino14** [S7NetPlus/s7netplus#503]
I have not found any method that can access the optimized DB. Is it possible that there is also no documentation on the web about this?

**Comment by SmackyPappelroy** [comment]
I have had same issue with optimized blocks. I was unable to find any documentation how the optimzed protocol works. I solved it using OPC-communication. Most new S7-15XX CPU's have the possibility to act as an OPC-server.
